### ISSUE TITLE
Switches and functions

### ISSUE THREAD

**Issue by nataliia-kulatska** [Hafro/gadget#15]
I was just wondering of the order of values in mathematical operations. Multiplication is easy, but what if we divide. In case (/ #a #b) would #a be divided by #b or #b divided by #a?

**Comment by bthe** [comment]
`(/ #a #b)` results in `a/b`. But you may find it useful to use the `to.gadget.formula` function from Rgadget to define more complicated formulas:
```
to.gadget.formulae(quote(linf*(1-exp(-1*k*(t-t0))))) 
[1] "(* #linf (- 1 (exp (* (* (- 1) #k) (- #t #t0)))))"
```

**Comment by nataliia-kulatska** [comment]
Great, that's useful. Thank you a lot!
