### ISSUE TITLE
GLIBC version issues

### ISSUE THREAD

**Issue by pfrater** [Hafro/gadget#18]
I just git cloned and compiled the most recent version of GADGET. It works great for the example here: ftp://ftp.hafro.is/pub/reiknid/dst2/gadget/haddock2.1.05.tar.gz

but when I call gadget on my older models I get the following errors.

```
gadget: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by gadget)
gadget: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by gadget)
gadget: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by gadget)
```

Any idea what the issue is?

Thanks,
Paul

**Comment by bthe** [comment]
My guess there is a mix up with different binaries of gadget, try doing `which gadget` in the different model directories and see if these yield different results

**Comment by pfrater** [comment]
I don't think so. It happens even when I compile gadget in the directory (and don't add it to my path) then call model files using `./gadget -s`. This is on a shared cluster (IHPC Garpur) running CentOS, so I'm not sure if there is a problem with the versions on the system there or not.

**Comment by bthe** [comment]
My guess is on the setup of the cluster, you may want to contact the administrator. Just to double check does the same issue occur on the mfdb machine?

**Comment by pfrater** [comment]
That's the weird thing. I contacted the administrator initially before posting here. He replied saying that he could get a model to run with the following code:

```
module purge
module load gcc/6.1.0
git clone https://github.com/Hafro/gadget.git
cd gadget/
make
curl -O ftp://ftp.hafro.is/pub/reiknid/dst2/gadget/haddock2.1.05.tar.gz
tar -xvf haddock2.1.05.tar.gz
cd haddock
../gadget -s -i refinputfile 
```

I was able to replicate this on the garpur cluster and it worked fine, so not sure what the issue is. But when I try it with an older model that I set up (gulllax) I get the errors initially alluded to. I do not have this problem on mfdb server...everything runs fine there.

**Comment by bthe** [comment]
I'm guessing the issue is related to the module which is (or is not) loaded on the Garpur cluster, see http://www.hpc.cam.ac.uk/using-clusters/user-environment-and-modules . Looking at this one would assume that you need to make sure that the gcc module is available when running gadget.
