### ISSUE TITLE
add stomach LH data

### ISSUE THREAD

**Issue by vbartolino** [Hafro/gadget#2]
I'm trying to add a stomach LH in a 2 species model (cod-sprat). I've tried 1 simulation in the terminal, I continue to get the same error and I haven't been able to figure out the reason.
Thankful for any suggestion where to look.

Finished reading model data files, starting to run simulation
Error when checking length structure for the following lengthgroups
Minimum length of length group division is 1
Maximum length of length group division is 137
Minimum length of length group division is 20
Maximum length of length group division is 100
Error in predatoraggregator - invalid predator length group structure

This is how I've set the lengths in the stockfiles and aggrfiles:
- cod.stock minlength, maxlength, bin: 1, 137, 2
- predator aggrfile
  len20   20  40
  len40   40  60
  len60   60  80
  len80   80  100
- stomachData
  ;year step area predator prey ratio
  2007    4 area1      len20     sprat10 0.012820513
  2007    4 area1      len20     sprat11 0.012820513
  2007    4 area1      len20     sprat12 0.029914530
  as predator I've used the label in the predator aggrfile (and similarly for the prey)

**Comment by bthe** [comment]
I guess your problem is related to the definition of length bins. The aggregation file doesn't match your definition of length bin for the stock. That is the stock dynamics is calculated in terms of odd numbers while the predator agg file is in even numbers.

**Comment by jmbegley** [comment]
It's some time since I looked at this, but isn't the problem the fact that the predator aggregation bins start at 20cm but the stock is defined down to 1cm (and the maximum length in the aggregation file is 100cm but the stock is defined up to 137cm)? If you create a new entry in the predator aggregation file of "len10 1 20" (for example) and another one for the maximum lengths of "len100 100 137" does it get a little further?

**Comment by vbartolino** [comment]
Yes, the mismatch between the length bin in the stock and the aggregation file (odd and even numbers) was the cause. As far  as I can see the min and max length in the predator aggregation file do not have to be the same as in the stock file (which make sense to me).
Thanks for the prompt and effective reply.

James, nice to see you back on the old good Gadget :)
