### ISSUE TITLE
Problem with variable growth over time

### ISSUE THREAD

**Issue by alfonsoperezrodriguez** [Hafro/gadget#24]
Gadget models growth by year, while we know that the growth function should be modelled by cohort. This is not a problem if growth (size at age) is constant over time. All cohorts would have the same growth curve, and hence no strong deviations (observed-estimated size at age) would be expected if growth is modeled by year instead of by cohort. 

However, when the growth rate at age changes over time (changes in growth between cohorts, induced by density dependence, strong water temperature changes, food availability...) the mean size at age in the stock will be very different from the mean size at age estimated by the Beverton and Holt modeled annually in gadget. Even worse, it is common that a few consecutive cohorts experience similar factors affecting growth and hence will have similar growth curves. This will be translated in a clear patterns with consecutive years of higher or lower size at age than that predicted by the annual beverton and holt curve. 

This problem can be very serious since it can produce strong deviations of the estimated population size distribution by gadget from those observed in the data (survey or catches), which, once translated to biomass can suppose strong differences in the total estimated stock biomass and spawning stock biomass (which is very affected by the growth function). A 10 cm difference in size may imply 1-2 kg of biomass per individual depending on the fish size and the species.

In XSA each age is assigned an average weight that comes from survey and commercial data. Is there any possiblity to assigned by hand an average weight by timestep (either year, season or month) by hand so the problems derived from changes in growth over time is avoided?

Thanks in advance.
Alfonso.

**Comment by bthe** [comment]
Forcing certain mean lengths and weights by age, a la XSA, is not implemented in Gadget. As I read your question you essentially want to be able to specify growth on a cohort basis. To implement this you have essentially two options:

* estimate variable recruitment length, which for haddock goes a long way in dealing with differences in the growth rates between cohorts. 
* define a separate substock for each cohort and estimate the growth parameters for each substock

**Comment by alfonsoperezrodriguez** [comment]
Thanks Bjarki
