### ISSUE TITLE
maximum consumption, request clarification

### ISSUE THREAD

**Issue by vbartolino** [Hafro/gadget#3]
I'm working with the consumption module in Gadget. The manual says "Note that the maximum consumption should be specified in kilojoules per month" (explanation for eq. 4.22).
Is it really "per month" or should it be "per timestep"?

Thanks for any clarification
\Valerio

**Comment by bthe** [comment]
Yes, see lines 157 to 162 in src/stockpredator.cc. Btw. you can also define substeps (intrastep steps) which is a functionality that I have never noticed before. Maybe @jmbegley can shed some light on that.
