### ISSUE TITLE
Cygwin 64 runs "gadget <options>" returns syntax error

### ISSUE THREAD

**Issue by mingsun** [Hafro/gadget#31]
Hi I am using Cygwin64 on windows 10 to run the gadget.

After I have successfully installed the executable file when I run "gadget <options>" as suggested from the Userguide, it returns "-bash: syntax error near unexpected token `newline'". 

Do you know what is going wrong here?

**Comment by pfrater** [comment]
My guess is that you just forgot a required parameter in the main, params, or another file. Try running it with the -log logfile.txt switch and see if you can debug the problem in that file.

**Comment by mingsun** [comment]
Thank you for your reply, pfrater.

I was actually following the Userguide 1.3 running gadget. So looks like I still have to have all the basic input well prepared before I run this command? I thought I could try this command before doing others.

**Comment by bthe** [comment]
I'll close this comment for now, gadget can now be installed as an R-package on windows.
