### ISSUE TITLE
Multi-area surveyindex fails when missing data

### ISSUE THREAD

**Issue by bthe** [Hafro/gadget#8]
Gadget has a problem with incomplete survey index data when number of areas is larger than 1 and data is not consistently missing within the same likelihood component. E.g. in a three area model the following datafile would result in a likelihood score of 1*10^10 regardless of the parametervalue:

```
; Generated by mfdb 4.0.0
; -- data --
; year  step    area    length  number
1976    1   area3   len40   310.4467
1978    1   area1   len40   155.255333333333
1978    1   area2   len40   235.7002725
1978    1   area3   len40   1209.91449
1979    1   area1   len40   1357.965
1979    1   area2   len40   458.677632
1979    1   area3   len40   1082.82543384615
1980    1   area2   len40   350.74494
1980    1   area3   len40   1388.49823636364
```

A easy fix for this problem is to split the likelihood components by area but Gadget should handle this problem more elegantly.

**Comment by AvTe** [comment]
this problem is to split the likelihood components by area but Gadget should handle this problem more elegantly.
